image: alpine:latest

pages:
  stage: deploy
  script:
  - wget https://github.com/cobalt-org/cobalt.rs/releases/download/v0.15.4/cobalt-v0.15.4-x86_64-unknown-linux-gnu.tar.gz
  - tar xvf cobalt-v0.15.4-x86_64-unknown-linux-gnu.tar.gz
  - cp cobalt /usr/bin/
  - cp cobalt /bin/
  - cobalt build -d public
  artifacts:
    paths:
    - public/
  only:
  - master
