image: ubuntu:latest

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get install -y wget make
  - wget https://github.com/cobalt-org/cobalt.rs/releases/download/v0.15.4/cobalt-v0.15.4-x86_64-unknown-linux-gnu.tar.gz
  - tar xvf cobalt-v0.15.4-x86_64-unknown-linux-gnu.tar.gz
  - make gitlab-ci
  artifacts:
    paths:
    - public/
  only:
  - master
  - dev
